## Load all packages used in the replication and print session info.
## Called at the start of run.sh to log the computational environment.

library(tidyverse)
library(lubridate)
library(brms)
library(cmdstanr)
library(bayesplot)
library(tidybayes)
library(ggdist)
library(kableExtra)
library(future)
library(furrr)
library(fixest)
library(texreg)
library(lme4)
library(sjlabelled)
library(rio)
library(tidylog)
library(scales)
library(GGally)
library(lqmm)
library(survey)
library(questionr)
library(Hmisc)
library(rstan)
library(arrow)
library(calibratedMRP)

cat("\n=== Session Info ===\n\n")
print(sessionInfo())
cat("\n=== cmdstan version ===\n")
cat(cmdstanr::cmdstan_version(), "\n")
